<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PhysicianNameValidation</name>
   <tag></tag>
   <elementGuidId>a0e8250c-ff88-44e4-9acc-2e8a89278157</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'CYNTHIA ABBOTT-JONES' or . = 'CYNTHIA ABBOTT-JONES')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;tbl_PhysicianList&quot;]/tbody/tr/td[1]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>datafld</name>
      <type>Main</type>
      <value>FName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CYNTHIA ABBOTT-JONES</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tbl_PhysicianList&quot;)/tbody[1]/tr[@class=&quot;HighLight&quot;]/td[1]/div[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//*[@id=&quot;tbl_PhysicianList&quot;]/tbody/tr/td[1]/div</value>
   </webElementXpaths>
</WebElementEntity>
