<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Admission Authorization Changes Report Link</name>
   <tag></tag>
   <elementGuidId>c81e0cd5-02c6-41e5-89a3-b9e7a45919b3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick=&quot;javascript:try{fnTrackRecordAccessReq(191,'Admission Authorization Changes Report',0,2,1773,287,150,'/backoffice/reports/reports.aspx');}catch(e){};fnOpenPage('Admission/AdmissionAuthChanges.aspx?mid=0&amp;ReportID=191&amp;ReportName=Admission Authorization Changes Report&amp;SpIndatabase=BU&amp;IsPortrait=False');&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>left</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30%</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bordercolor</name>
      <type>Main</type>
      <value>silver</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:try{fnTrackRecordAccessReq(191,'Admission Authorization Changes Report',0,2,1773,287,150,'/backoffice/reports/reports.aspx');}catch(e){};fnOpenPage('Admission/AdmissionAuthChanges.aspx?mid=0&amp;ReportID=191&amp;ReportName=Admission Authorization Changes Report&amp;SpIndatabase=BU&amp;IsPortrait=False');</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Admission Authorization Changes Report</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;REPORT191&quot;)/td[@class=&quot;link&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//td[@onclick=&quot;javascript:try{fnTrackRecordAccessReq(191,'Admission Authorization Changes Report',0,2,1773,287,150,'/backoffice/reports/reports.aspx');}catch(e){};fnOpenPage('Admission/AdmissionAuthChanges.aspx?mid=0&amp;ReportID=191&amp;ReportName=Admission Authorization Changes Report&amp;SpIndatabase=BU&amp;IsPortrait=False');&quot;]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//tr[@id='REPORT191']/td[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Clients with No Visits Report'])[1]/following::td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active Clients By BDR And Status Report'])[1]/following::td[8]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Report gives Changes made to the Authorization details.'])[1]/preceding::td[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Admits by Payer Source Report'])[1]/preceding::td[4]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//tr[4]/td[2]</value>
   </webElementXpaths>
</WebElementEntity>
