<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>DrugClass</name>
   <tag></tag>
   <elementGuidId>a13cb4f4-37f1-448e-ba8d-36db3660584d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cmb_mpAllergy_Dialog_DrugClass']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cmb_mpAllergy_Dialog_DrugClass</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>&lt;Select>5-Alpha Reductase Inhibitors5HT3 Receptor AntagonistsAbacavirACE InhibitorsAcetaminophenAcyclovir and RelatedAlbumin (Human)Allergy History Not KnownAllergy History Refused by PatientAllopurinolAlpha Blocker QuinazolinesAluminum-containing CompoundsAmantadinesAmilorideAminoglycosidesAminolevulinate DerivativesAminopyridinesAminoquinolinesAminothiolsAmiodaroneAmmonium-containing CompoundsAmoxapine and RelatedAmphetaminesAmphotericin BAmprenavirAndrogensAnesthetics, AmideAnesthetics, EsterAnesthetics, HalogenatedAngiotensin Receptor BlockersAnthracyclinesAntihistamines, Chlorpheniramine-typeAntihistamines, Diphenhydramine-typeAntihistamines, Loratadine-typeAntimony-containing CompoundsAprepitant &amp; RelatedAscorbic Acid &amp; DerivativesAsparaginase DerivativesAspartame and PhenylalanineAtazanavirAtracurium &amp; DerivativesAztreonamBarbituratesBarium-containing CompoundsBeef-derived ProductsBelladonna AlkaloidsBenzamide DerivativesBenzimidazole AntihelminthicsBenzodiazepinesBenzyl AlcoholBeta Adrenergic BlockersBeta-2 AgonistsBile SaltsBismuth-containing CompoundsBisphosphonatesBlue Dyes (Parenteral)BoronBotulinum ToxinsBupropionBusulfanC1 Esterase InhibitorsCalcium Channel BlockersCalcium-containing CompoundsCannabinoidsCarbamatesCarbamazepine and AnalogsCarbapenemsCellulose-related CompoundsCephalosporinsCetirizine &amp; RelatedChlorambucil DerivativesChloramphenicolsCholera VaccinesCholinesterase InhibitorsChromiumCimetidineClavulanic AcidClindamycin/LincomycinClonidine DerivativesCobaltCobicistatColistin and relatedCopper-containing CompoundsCorn-containing ProductsCorticosteroidsCOX-2 InhibitorsCremophor Containing DrugsCyclobenzaprineCyclosporineDacarbazine and RelatedDapsoneDasabuvirDextransDideoxynucleosidesDigoxin and RelatedDipeptidyl Peptidase-4 Inhibitors (Gliptins)Diphtheria Toxoid-containing VaccinesDolutegravirEchinocandin AntifungalsE-Coli-derived ProductsEfavirenzEggs or Egg-derived ProductsElbasvirElvitegravirErgot AlkaloidsEstrogensEszopiclone and RelatedEthanolEthionamide and ProtionamideEthylenediamineFentanyl and RelatedFibratesFish-derived ProductsFluoride PreparationsFluorouracilFosfomycinGadolinium DerivativesGlecaprevirGlucocerebrosidase ReplenishersGlutethimidesGlycopyrrolateGoat-derived ProductsGold-containing Drug ProductsGonadotropin RH AnalogsGrazoprevirGreen DyesGriseofulvinGuaifenesin &amp; DerivativesH2 AntagonistsHaemophilus Influenzae VaccinesHaloperidol and RelatedHeparinHepatitis B Virus VaccineHirudin AnalogsHorse-derived ProductsHuman G-CSFHydantoinsHydroxyquinolinesImidazole AntifungalsImmune GlobulinsIncretin Mimetic AgentsIndanedionesInfluenza VaccinesInhaled Anticholinergic AgentsInsulinsInterferonsIodidesIodinated Diagnostic AgentsIrinotecanIronIsoniazidIsosorbideKetamine and relatedLactose Intolerance (GI)LamotrigineLeflunomide and RelatedLevodopaLithiumLMW HeparinLoop DiureticsLumiracoxibMacrolides and KetolidesMagnesium-containing CompoundsManganeseMeningococcal and Conjugated VaccinesMeperidine and RelatedMercurial DerivativesMetformin and RelatedMethadoneMethotrexate DerivativesMethylisothiazolinoneMethylphenidate DerivativesMetoclopramideMetronidazole and RelatedMilk-related CompoundsMilnacipran and RelatedMilrinone and RelatedMisc. Sulfonamide Containing CompoundsModafinil and RelatedMonkey-derived ProductsMonoclonal AntibodiesMorphine and RelatedMouse-derived ProductsNaloxoneNaltrexoneNeomycin-containing Injectable ProductsNeuromuscular Blocking AgentsNiacin and RelatedNitrates, OrganicNitrofuran DerivativesNo Known Drug AllergyNo Known Environmental AllergiesNo Known Food AllergyNo Known Latex AllergyNSAIDsOmbitasvirPABA DerivativesPapaya DerivativesParabensParasympathomimeticsParitaprevirPeanut-containing Drug ProductsPegylated Drug ProductsPenicillinsPentazocinePersulfatesPertussis VaccinesPhenothiazinesPhenylbutazonesPibrentasvirPlatinum-containing CompoundsPneumococcal VaccinesPodophyllotoxinsPolyethylene GlycolPolysorbatePork-derived ProductsPotassium-containing CompoundsProgestinsPropoxypheneProstaglandinsProtamineProton Pump InhibitorsPsylliumQuinine DerivativesQuinolonesRabbit-derived ProductsRabies VaccinesRauwolfia DerivativesRed DyeRetinoidsRifamycinsRilpivirineRisperidone and RelatedRitonavirSalicylatesSelected Herbal MedicinesSelective Estrogen Receptor ModulatorsSeleniumSerotonin Reuptake Inhibitors (SSRIs)SGLT2 InhibitorsSheep-derived ProductsShellfish-derived ProductsSilverSirolimus and RelatedSofosbuvirSoybean-containing Drug ProductsSpironolactoneStatinsStreptograminsStreptokinasesStreptomycin (obsolete)StrontiumSulfa AntibioticsSulfinpyrazoneSulfitesSulfonylureasSympathomimeticsSynthetic CannabinoidsTartrazineTeicoplaninTenofovirTerbinafine and RelatedTetanus ToxoidsTetracyclines &amp; RelatedThalidomide and RelatedTheophyllinesThiazide-Type DiureticsThienopyridinesThimerosalThioamidesThioxanthenesThyroid HormonesTitaniumTolterodine and RelatedTopical SulfurTramadolTrazodone and NefazodoneTriamtereneTricyclic AntidepressantsTrimethoprimTriptansTuberculin TestsTumor Necrosis Factor AntagonistsTyphoid VaccinesUncoded Nonscreenable AllergenUndecylenatesUreasValproic Acid and RelatedVancomycinVelpatasvirVenlafaxine &amp; RelatedVinca AlkaloidsVitamin D AnalogsVitamin K and RelatedVoxilaprevirWarfarin and RelatedYeast-related ProductsYellow Dyes (Non-tartrazine)ZidovudineZinc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cmb_mpAllergy_Dialog_DrugClass&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='cmb_mpAllergy_Dialog_DrugClass']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='tr_allergyTypeClass']/div[2]/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drug Class:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[8]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drug Name:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Drug:'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[2]/div[2]/select</value>
   </webElementXpaths>
</WebElementEntity>
