<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AssessmentList</name>
   <tag></tag>
   <elementGuidId>67f654ba-94da-432b-ab67-5acfeeb80c87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='assessment-slct']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>assessment-slct</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a paraprofessional assignment sheet_MULTIBUTEST_OASISC2_SOC0TEST0TEST copyA_Conditional Section FormABC Basic Formaid assessmentAide visit note (other form type) Animal Stress for Summer Therapy  (Testing Form CnArt TherapyASMITTOTESTATestAutomotive Service Form (Sport Cars Enthusiast Basic Form Clone with P&amp;IBasic Form Cnu Testing 1234bwtestCLNK-24183Death at Home Assessment - NEWDeath at Home Assessment (C2)Death at Home Assessment (D)Death at Home Assessment (D) - ASMITTODeath at Home Assessment NEW CloneDischarge Assessment and Discharge Summary Adult Care (Non OASIS)Discharge Assessment and Discharge Summary Adult Care (Non OASIS) copyDischarge for Paraprofessional ServicesDischarge from agencyDischarge from agency (C2)Discharge from agency (C2) cloned assessmentDischarge from agency (D)Discharge from agency (D) copyDischarge from agency (D) copyDischarge PlanDog Veterinarian   Testing CnuDog Veterinarian   Testing Cnu copy (Clone copy) CDuPage Animal Intake Faith's test reportFollow-Up Depression ScreeningFollow-Up/Resumption of Care Skilled Adult AssessmentInitial Depression screeningLabel_Testmedication administrationMSW AssessmentMy New form to testNew Test FormNursing Assessment(Non Oasis)  non skilledOccupational Therapy AssessmentOther follow-upOther follow-up (C2)Other follow-up (D)Pediatric AssessmentPediatric Assessment DischargePediatric Comprehensive AssessmentPediatric Comprehensive Initial AssessmentPediatric Comprehensive Therapy AssessmentPediatric Occupational Therapy EvaluationPediatric Physical Therapy EvaluationPediatric Speech Therapy EvaluationPediatric Speech Therapy Evaluation NEW CLONEPhysical Therapy Assessment with BERG Balance ScorePhysical Therapy Evaluation and Plan of CarePhysical Therapy Evaluation and Plan of Care (Cnu)PIG TestPsychiatric Assessment AddendumRecertification (Follow-up) AssessmentRecertification (Follow-up) Assessment (C2)Recertification (Follow-up) Assessment (D)Resumption of care (after inpatient Stay)Resumption of care (after inpatient Stay)Resumption of care (after inpatient Stay) (C2)Resumption of care (after inpatient Stay) (D)Resumption of care (after inpatient Stay) (D) 26887Risk AssessmentRisk Assessment copySample (Laura) Shaw Testing Form for CLNK-21717Speech Therapy AssessmentSpeech Therapy Assessment copyStart of care - further visits plannedStart of care - further visits plannedStart of care - further visits planned - BROKENStart of care - further visits planned - Broken2 (Start of care - further visits planned (C2)Start of care - further visits planned (C2)Start of care - further visits planned (C2) copyStart of care - further visits planned (D)Start of care - further visits planned (D) 26692Start of care - further visits planned (D) copyStart of care - further visits planned (D)_26665Start of care - further visits planned (D)_26692Start of Care Skilled Adult Assessment(Non Oasis) Start of Care/Follow-Up Paraprofessional AssessmentSupplies in Back officeTEST DEMOtest formTest Label control formTest OxygenTest RefreshingTesting Cnu Therapy Assessment and Plan of CareTransfer to an inpatient facility - Patient not diTransfer to an Inpatient Facility - patient not discharged from agencyTransfer to an Inpatient Facility - patient not discharged from agencyTransfer to an inpatient facility - Patient not discharged from agency (C2)Transfer to an inpatient facility - Patient not discharged from agency (D)Transfer to inpatient facility - Patient discharged from agencyTransfer to inpatient facility - Patient discharged from agency (C2)Transfer to inpatient facility - Patient discharged from agency (D)Visit Notes Addendum clone copyWound Form</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;assessment-slct&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <value>//select[@id='assessment-slct']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <value>//div[@id='divModalAddAssessment']/div/div/select</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assessment:'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Show OASIS types only'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Date:'])[5]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <value>//div[7]/div[2]/div/div/select</value>
   </webElementXpaths>
</WebElementEntity>
